# Generated by Django 2.1.3 on 2018-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='idcustomer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='idpicture',
            field=models.IntegerField(),
        ),
    ]
